services:

  docker_spring_boot:
    container_name: docker-spring-boot
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp
    ports:
      - "8080:8080"
    networks:
      - bosonit-backend

  postgres_db:
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=contrasena
    depends_on:
      - "docker_spring_boot"
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - bosonit-backend

networks:
  bosonit-backend:
    driver: bridge