  # ---- Docker compose ----
  version: '3.8'

  services:

    db:
      image: postgres:15.2
      container_name: springadvanced
      restart: always
      volumes:
        - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
        - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
      environment:
        - POSTGRES_DB=springadvanced
        - POSTGRES_USER=abarj
        - POSTGRES_PASSWORD=1234
      ports:
        - "5432:5432"

    # ---- Docker command ----
    # sudo docker run --name springadvanced -p 5432:5432 -e  POSTGRES_DB=springadvanced -e POSTGRES_USER=abarj -e POSTGRES_PASSWORD=1234 -v ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql -v ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql postgres:latest

    cache-db:
      image: redis:6.2-alpine
      container_name: springadvanced_cache
      restart: always
      ports:
        - "6379:6379"
      command: redis-server --loglevel warning --requirepass 1234

      # ---- Docker comand ----
      # docker run --name springadvanced_cache -p 6379:6379 -e REDIS_ARGS="--requirepass 1234" redis:6.2-alpine

    document-db:
      image: mongo:6.0.4
      restart: always
      container_name: springadvanced_users
      environment:
        MONGO_INITDB_ROOT_USERNAME: master
        MONGO_INITDB_ROOT_PASSWORD: 1234
        MONGO_INITDB_DATABASE: app_users
      ports:
        - "27017:27017"
      volumes:
        - ./db/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

      # ---- Docker command ----
      # docker run --name springadvanced_document -p 27017:27017 -e  MONGO_INITDB_ROOT_USERNAME=master -e MONGO_INITDB_ROOT_PASSWORD=1234 -e MONGO_INITDB_DATABASE=users -v ./db/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro mongo:6.0.4